version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/dbname"

  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  db: